- migrations/1_initial_migration.js
- migrations/2_deploy_contract.js
- migrations/helpers.js
Usage:
`truffle migrate [--reset] [--filter filter1[,filter2,...]]`
Where `filter#` is the name of the SC to deploy. Wildcards accepted and more than one filter can be added, separated by a `,`.
> Added filtered deployment

- migrations/1_initial_migration.js
- migrations/2_deploy_contract.js
- migrations/helpers.js
- test/scenarios/DriipSettlementChallenge.js
Add deployment of missing FraudChallengeByTradeOrderResiduals
> WIP: Updates on deployment

- contracts/CancelOrdersChallenge.sol
- contracts/DriipSettlementChallenge.sol
- contracts/DriipSettlementChallenger.sol
- contracts/Exchange.sol
- contracts/FraudChallengable.sol
- contracts/FraudChallenge.sol
- contracts/RevenueFund.sol
- contracts/Validatable.sol
- contracts/test/UnitTestHelpers.sol
The included updates errors that prevented compilation of smart contracts. Some of the fixes are temporary and not complete and are annotated with TODOs.
> Fixes following multiple token standard support

- contracts/Beneficiary.sol
- contracts/ClientFund.sol
- contracts/PartnerFund.sol
- contracts/RevenueFund.sol
- contracts/SecurityBond.sol
- migrations/2_deploy_contract.js
PartnerFund, RevenueFund and SecurityBond have been disabled from
deployment as they have not been updated with two-component currency
descriptors.
> Updates to Beneficiary.depositTokensTo()

- contracts/Configuration.sol
- contracts/DriipSettlementChallenge.sol
- contracts/DriipSettlementChallenger.sol
- contracts/FraudChallengeByDoubleSpentOrders.sol
- contracts/FraudChallengeByDuplicateDriipNonceOfPayments.sol
- contracts/FraudChallengeByDuplicateDriipNonceOfTradeAndPayment.sol
- contracts/FraudChallengeByDuplicateDriipNonceOfTrades.sol
- contracts/FraudChallengeByOrder.sol
- contracts/FraudChallengeByPayment.sol
- contracts/Validator.sol
- package-lock.json
- test/main.js
- test/scenarios/Configuration.js
- test/scenarios/DriipSettlementChallenge.js
- test/scenarios/DriipSettlementChallenger.js
- test/scenarios/FraudChallengeByDoubleSpentOrders.js
- test/scenarios/FraudChallengeByDuplicateDriipNonceOfPayments.js
- test/scenarios/FraudChallengeByDuplicateDriipNonceOfTradeAndPayment.js
- test/scenarios/FraudChallengeByDuplicateDriipNonceOfTrades.js
- test/scenarios/FraudChallengeByOrder.js
- test/scenarios/FraudChallengeByPayment.js
- test/scenarios/Validator.js
Update of _Configuration_ is focus in this PR. A number of TODOs have been added in other contracts where remaining work is needed in order to fully support two-component currency descriptors.
> Add support for two-component currency descriptor in Configuration

- contracts/Configuration.sol
- test/scenarios/Configuration.js
The number of confirmations associated with on-chain finality.
> Add confirmations getter and setter

- contracts/Exchange.sol
- contracts/StriimTypes.sol
- test/scenarios/Exchange.js
> Settlement accessors

- contracts/AccessorManageable.sol
- contracts/Configurable.sol
- contracts/Ownable.sol
- package.json
- test/scenarios/AuthorizableServable.js
- test/scenarios/CancelOrdersChallenge.js
- test/scenarios/Configuration.js
- test/scenarios/DriipSettlementChallenge.js
- test/scenarios/DriipSettlementDispute.js
- test/scenarios/Exchange.js
- test/scenarios/FraudChallenge.js
- test/scenarios/FraudChallengeByDoubleSpentOrders.js
- test/scenarios/FraudChallengeByDuplicateDriipNonceOfPayments.js
- test/scenarios/FraudChallengeByDuplicateDriipNonceOfTradeAndPayment.js
- test/scenarios/FraudChallengeByDuplicateDriipNonceOfTrades.js
- test/scenarios/FraudChallengeByOrder.js
- test/scenarios/FraudChallengeByPayment.js
- test/scenarios/FraudChallengeByPaymentSucceedingTrade.js
- test/scenarios/FraudChallengeBySuccessivePayments.js
- test/scenarios/FraudChallengeBySuccessiveTrades.js
- test/scenarios/FraudChallengeByTrade.js
- test/scenarios/FraudChallengeByTradeOrderResiduals.js
- test/scenarios/FraudChallengeByTradeSucceedingPayment.js
- test/scenarios/Servable.js
Partial implementation of #190.
> Finalize unit tests after ACL update

- contracts/Exchange.sol
- test/scenarios/Exchange.js
> Stage net fee event

- contracts/DriipSettlement.sol
- contracts/DriipSettlementChallenge.sol
- contracts/DriipSettlementDispute.sol
- contracts/FraudChallengeByPaymentSucceedingTrade.sol
- contracts/FraudChallengeBySuccessivePayments.sol
- contracts/FraudChallengeBySuccessiveTrades.sol
- contracts/FraudChallengeByTradeOrderResiduals.sol
- contracts/FraudChallengeByTradeSucceedingPayment.sol
- contracts/NahmiiTypes.sol
- contracts/Validatable.sol
- contracts/Validator.sol
> Move functions in NahmiiTypes to Validator

- contracts/ClientFund.sol
- contracts/ClientFundable.sol
- contracts/ERC20TransferController.sol
- contracts/ERC721TransferController.sol
- contracts/PartnerFund.sol
- contracts/SecurityBond.sol
- contracts/TokenHolderRevenueFund.sol
- contracts/TransferController.sol
- contracts/test/MockedClientFundService.sol
- contracts/test/StandardTokenEx.sol
- test/main.js
- test/scenarios/ClientFund.js
- test/scenarios/ERC20TransferController.js
> Client fund updates

- contracts/AuthorizableServable.sol
- contracts/ClientFund.sol
- contracts/Servable.sol
- migrations/2_deploy_contract.js
- test/scenarios/AuthorizableServable.js
- test/scenarios/Configuration.js
- test/scenarios/DriipSettlementDispute.js
- test/scenarios/RevenueFund.js
- test/scenarios/SecurityBond.js
- test/scenarios/SignerManager.js
- test/scenarios/TokenHolderRevenueFund.js
> Initially authorized services

- contracts/Configuration.sol
- contracts/DriipSettlementDispute.sol
- contracts/FraudChallengeByDoubleSpentOrders.sol
- contracts/FraudChallengeByDuplicateDriipNonceOfPayments.sol
- contracts/FraudChallengeByDuplicateDriipNonceOfTradeAndPayment.sol
- contracts/FraudChallengeByDuplicateDriipNonceOfTrades.sol
- contracts/FraudChallengeByOrder.sol
- contracts/FraudChallengeByPayment.sol
- contracts/InUseCurrencyLib.sol
- contracts/SecurityBond.sol
- contracts/TokenHolderRevenueFund.sol
- contracts/test/MockedDriipSettlementDispute.sol
- contracts/test/MockedSecurityBond.sol
- contracts/test/MockedSecurityBondService.sol
- contracts/test/UnitTestHelpers.sol
- migrations/2_deploy_contract.js
- test/scenarios/Configuration.js
- test/scenarios/DriipSettlementDispute.js
- test/scenarios/FraudChallengeByDoubleSpentOrders.js
- test/scenarios/FraudChallengeByDuplicateDriipNonceOfPayments.js
- test/scenarios/FraudChallengeByDuplicateDriipNonceOfTradeAndPayment.js
- test/scenarios/FraudChallengeByDuplicateDriipNonceOfTrades.js
- test/scenarios/FraudChallengeByOrder.js
- test/scenarios/FraudChallengeByPayment.js
- test/scenarios/SecurityBond.js
> Fractional stakes

- contracts/AccrualBenefactor.sol
- contracts/Benefactor.sol
- contracts/DriipSettlementDispute.sol
- contracts/ERC20TransferController.sol
- contracts/ERC721TransferController.sol
- contracts/NullSettlementDispute.sol
- contracts/PartnerFund.sol
- contracts/RevenueFund.sol
- contracts/RevenueToken.sol
- contracts/SignerManager.sol
- contracts/TokenHolderRevenueFund.sol
- contracts/TransferControllerManager.sol
Solution to #192.
The old RevenueToken `holdersEnum()` was replaced by `holdersByIndices(uint256 low, uint256 up)`.
> Revenue token holders by indices

- contracts/AuthorizableServable.sol
- test/scenarios/AuthorizableServable.js
> Opt-out to opt-in

- contracts/ClientFund.sol
- contracts/Configuration.sol
- contracts/DriipSettlementDispute.sol
- contracts/FraudChallengeByPayment.sol
- contracts/FraudChallengeByPaymentSucceedingTrade.sol
- contracts/FraudChallengeBySuccessivePayments.sol
- contracts/FraudChallengeBySuccessiveTrades.sol
- contracts/FraudChallengeByTrade.sol
- contracts/FraudChallengeByTradeOrderResiduals.sol
- contracts/FraudChallengeByTradeSucceedingPayment.sol
- contracts/NullSettlementDispute.sol
- contracts/test/MockedClientFund.sol
- contracts/test/MockedClientFundService.sol
- migrations/3_bulk_of_contract.js
- test/scenarios/ClientFund.js
- test/scenarios/Configuration.js
- test/scenarios/DriipSettlementDispute.js
- test/scenarios/FraudChallengeByPayment.js
- test/scenarios/FraudChallengeByPaymentSucceedingTrade.js
- test/scenarios/FraudChallengeBySuccessivePayments.js
- test/scenarios/FraudChallengeBySuccessiveTrades.js
- test/scenarios/FraudChallengeByTrade.js
- test/scenarios/FraudChallengeByTradeOrderResiduals.js
- test/scenarios/FraudChallengeByTradeSucceedingPayment.js
- test/scenarios/NullSettlementDispute.js
- test/scenarios/Validator.js
> Lock balances

- migrations/1_initial_migration.js
- migrations/2_nahmii_token.js
- migrations/3_bulk_of_contract.js
> Token address and configuration initialization

- contracts/Ownable.sol
- contracts/SelfDestructible.sol
> Disable self-destruction

- contracts/Hasher.sol
- migrations/3_bulk_of_contract.js
- test/mocks.js
> Total fees in driip hashes

- contracts/RevenueTokenManager.sol
- contracts/TokenMultiTimelock.sol
- test/scenarios/RevenueTokenManager.js
- test/scenarios/TokenMultiTimelock.js
> Allow calls by beneficiary instead of operator

- contracts/DriipSettlementChallengeByPayment.sol
- contracts/DriipSettlementChallengeByTrade.sol
- contracts/DriipSettlementChallengeState.sol
- contracts/DriipSettlementDisputeByPayment.sol
- contracts/DriipSettlementDisputeByTrade.sol
- contracts/NullSettlementChallengeByPayment.sol
- contracts/NullSettlementChallengeByTrade.sol
- contracts/NullSettlementChallengeState.sol
- contracts/NullSettlementDisputeByPayment.sol
- contracts/NullSettlementDisputeByTrade.sol
- contracts/SettlementChallengeTypesLib.sol
- contracts/test/MockedDriipSettlementChallengeState.sol
- contracts/test/MockedNullSettlementChallengeState.sol
- test/scenarios/DriipSettlementChallengeByPayment.js
- test/scenarios/DriipSettlementChallengeByTrade.js
- test/scenarios/DriipSettlementChallengeState.js
- test/scenarios/DriipSettlementDisputeByPayment.js
- test/scenarios/DriipSettlementDisputeByTrade.js
- test/scenarios/NullSettlementChallengeByPayment.js
- test/scenarios/NullSettlementChallengeByTrade.js
- test/scenarios/NullSettlementChallengeState.js
- test/scenarios/NullSettlementDisputeByPayment.js
- test/scenarios/NullSettlementDisputeByTrade.js
> Stop settlement processes

- contracts/DriipSettlementChallengeByPayment.sol
- contracts/DriipSettlementChallengeByTrade.sol
- test/scenarios/DriipSettlementChallengeByPayment.js
- test/scenarios/DriipSettlementChallengeByTrade.js
- test/scenarios/FraudChallengeByOrder.js
> Settlement challenge ordinality

- contracts/DriipSettlementDisputeByPayment.sol
- contracts/DriipSettlementDisputeByTrade.sol
- contracts/FraudChallengeByPayment.sol
- contracts/FraudChallengeByPaymentSucceedingTrade.sol
- contracts/FraudChallengeBySuccessivePayments.sol
- contracts/FraudChallengeBySuccessiveTrades.sol
- contracts/FraudChallengeByTrade.sol
- contracts/FraudChallengeByTradeOrderResiduals.sol
- contracts/FraudChallengeByTradeSucceedingPayment.sol
- contracts/NullSettlementDisputeByPayment.sol
- contracts/NullSettlementDisputeByTrade.sol
- contracts/WalletLocker.sol
- contracts/test/MockedWalletLocker.sol
- test/scenarios/DriipSettlementDisputeByPayment.js
- test/scenarios/FraudChallengeByPayment.js
- test/scenarios/FraudChallengeByPaymentSucceedingTrade.js
- test/scenarios/FraudChallengeBySuccessivePayments.js
- test/scenarios/FraudChallengeBySuccessiveTrades.js
- test/scenarios/FraudChallengeByTrade.js
- test/scenarios/FraudChallengeByTradeOrderResiduals.js
- test/scenarios/FraudChallengeByTradeSucceedingPayment.js
- test/scenarios/NullSettlementDisputeByPayment.js
- test/scenarios/WalletLocker.js
> Delayed visibility in locks

- contracts/BalanceTrackerLib.sol
- contracts/FraudChallengeBySuccessivePayments.sol
- contracts/NullSettlementChallengeByPayment.sol
- contracts/NullSettlementChallengeByTrade.sol
- contracts/Validator.sol
- contracts/ValidatorV2.sol
- contracts/test/MockedBalanceTracker.sol
- contracts/test/MockedValidator.sol
- migrations/3_libraries.js
- migrations/5_bulk_of_contract.js
- test/scenarios/FraudChallengeBySuccessivePayments.js
- test/scenarios/NullSettlementChallengeByPayment.js
- test/scenarios/NullSettlementChallengeByTrade.js
> Support for active balance update between successive payments in fraud challenge

- contracts/FraudChallengeBySuccessivePayments.sol
- contracts/FraudChallengeBySuccessiveTrades.sol
- contracts/Validator.sol
- contracts/ValidatorV2.sol
- contracts/test/MockedValidator.sol
- migrations/5_bulk_of_contract.js
- test/scenarios/FraudChallengeBySuccessivePayments.js
- test/scenarios/FraudChallengeBySuccessiveTrades.js
> Support for active balance update between successive trades in fraud challenge

- contracts/FraudChallengeByPaymentSucceedingTrade.sol
- contracts/FraudChallengeBySuccessivePayments.sol
- contracts/FraudChallengeBySuccessiveTrades.sol
- contracts/FraudChallengeByTradeSucceedingPayment.sol
- contracts/NahmiiTypesLib.sol
- contracts/ValidatorV2.sol
- contracts/test/MockedValidator.sol
- migrations/5_bulk_of_contract.js
- test/scenarios/FraudChallengeByPaymentSucceedingTrade.js
- test/scenarios/FraudChallengeBySuccessivePayments.js
- test/scenarios/FraudChallengeBySuccessiveTrades.js
- test/scenarios/FraudChallengeByTradeSucceedingPayment.js
> Support active balance update between successive cross-type driips

- contracts/DriipSettlementChallengeByPayment.sol
- contracts/NullSettlementChallengeByPayment.sol
> Revise signature of events emitted at start of DSC by payment and NSC

- contracts/DriipSettlementChallengeState.sol
- contracts/NullSettlementChallengeState.sol
- test/scenarios/DriipSettlementChallengeState.js
- test/scenarios/NullSettlementChallengeState.js
> Add constraints on completed DSC per driip

- contracts/BalanceTrackerLib.sol
- contracts/DriipSettlementChallengeByPayment.sol
- contracts/DriipSettlementChallengeState.sol
- contracts/NullSettlementChallengeByPayment.sol
- contracts/Validator.sol
- contracts/ValidatorV2.sol
- contracts/test/MockedBalanceTracker.sol
- contracts/test/MockedDriipSettlementChallengeState.sol
- contracts/test/MockedNullSettlementChallengeState.sol
- migrations/5_bulk_of_contract.js
- test/scenarios/DriipSettlementChallengeByPayment.js
- test/scenarios/DriipSettlementChallengeState.js
- test/scenarios/NullSettlementChallengeByPayment.js
- test/scenarios/NullSettlementChallengeByTrade.js
> Revise start of DSC from payment

- contracts/BalanceTrackerLib.sol
- contracts/DriipSettlementChallengeByPayment.sol
- contracts/DriipSettlementChallengeByTrade.sol
- contracts/DriipSettlementChallengeState.sol
- contracts/DriipSettlementDisputeByTrade.sol
- contracts/NullSettlementChallengeByPayment.sol
- contracts/NullSettlementChallengeByTrade.sol
- contracts/NullSettlementChallengeState.sol
- contracts/SettlementChallengeTypesLib.sol
- contracts/test/MockedDriipSettlementChallengeState.sol
- contracts/test/MockedNullSettlementChallengeState.sol
- migrations/5_bulk_of_contract.js
- test/scenarios/DriipSettlementChallengeByPayment.js
- test/scenarios/DriipSettlementChallengeByTrade.js
- test/scenarios/DriipSettlementChallengeState.js
- test/scenarios/DriipSettlementDisputeByPayment.js
- test/scenarios/DriipSettlementDisputeByTrade.js
- test/scenarios/NullSettlementChallengeByPayment.js
- test/scenarios/NullSettlementChallengeByTrade.js
- test/scenarios/NullSettlementChallengeState.js
- test/scenarios/NullSettlementDisputeByPayment.js
- test/scenarios/NullSettlementDisputeByTrade.js
> Revise start of NSC in NullSettlementChallengeByPayment

- contracts/DriipSettlementDisputeByPayment.sol
- contracts/NullSettlementDisputeByPayment.sol
- migrations/5_bulk_of_contract.js
- test/scenarios/DriipSettlementDisputeByPayment.js
> Revise submission of payment candidate for DSC

- test/scenarios/DriipSettlementDisputeByPayment.js
> Update unit tests of DriipSettlementDisputeByPayment

- contracts/DriipSettlementChallengeState.sol
- contracts/DriipSettlementDisputeByPayment.sol
- contracts/NullSettlementChallengeState.sol
- contracts/test/MockedNullSettlementChallengeState.sol
- migrations/5_bulk_of_contract.js
- test/scenarios/DriipSettlementDisputeByPayment.js
- test/scenarios/NullSettlementChallengeState.js
> Cancel dependent NSC at successful submission of payment candidate in DSC

- contracts/NullSettlement.sol
- migrations/5_bulk_of_contract.js
- test/scenarios/NullSettlement.js
> No overlapping DSC and removal of NSC at null settlement

- contracts/DriipSettlementByPayment.sol
- contracts/DriipSettlementChallengeState.sol
- contracts/test/MockedDriipSettlementChallengeState.sol
- test/scenarios/DriipSettlementByPayment.js
- test/scenarios/DriipSettlementChallengeState.js
> Removal of DSC proposal at payment settlement

- contracts/DriipSettlementChallengeByPayment.sol
- test/scenarios/DriipSettlementChallengeByPayment.js
> Cancel overlapping NSC when cancelling DSC

- contracts/DriipSettlementChallengeByPayment.sol
- contracts/DriipSettlementChallengeState.sol
- contracts/NullSettlementChallengeByPayment.sol
- contracts/NullSettlementChallengeState.sol
- package.json
- sample/ClientFund.js
- sample/DriipSettlementChallengeByPayment.js
- sample/DriipSettlementDisputeByPayment.js
- sample/NullSettlementChallengeByPayment.js
- sample/NullSettlementDisputeByPayment.js
- sample/WalletLocker.js
- test/scenarios/DriipSettlementChallengeByPayment.js
- test/scenarios/NullSettlementChallengeByPayment.js
> Add ChallengeByPaymentEvent to {Driip,Null}SettlementChallengeByPayment

- contracts/RevenueFund.sol
- contracts/RevenueFund1.sol
- migrations/5_bulk_of_contract.js
- test/main.js
- test/scenarios/RevenueFund1.js
> Loosen driip type constraint on revenue fund

- contracts/DriipSettlementChallengeByPayment.sol
- contracts/DriipSettlementChallengeByTrade.sol
- contracts/DriipSettlementChallengeState.sol
- contracts/DriipSettlementDisputeByPayment.sol
- contracts/NullSettlementChallengeByPayment.sol
- contracts/NullSettlementChallengeByTrade.sol
- contracts/NullSettlementChallengeState.sol
- contracts/NullSettlementDisputeByPayment.sol
- contracts/SettlementChallengeTypesLib.sol
- contracts/test/MockedDriipSettlementChallengeState.sol
- contracts/test/MockedNullSettlementChallengeState.sol
- test/scenarios/DriipSettlementChallengeByPayment.js
- test/scenarios/DriipSettlementChallengeByTrade.js
- test/scenarios/DriipSettlementChallengeState.js
- test/scenarios/NullSettlementChallengeByPayment.js
- test/scenarios/NullSettlementChallengeByTrade.js
- test/scenarios/NullSettlementChallengeState.js
> Add definition block number to settlement proposal

- sample/DriipSettlementChallengeByPayment.js
- sample/NullSettlementChallengeByPayment.js
> Update sampling of stop challenge calls

- contracts/ClientFund.sol
- contracts/ERC20TransferController.sol
- contracts/ERC721TransferController.sol
- contracts/TransferController.sol
- test/scenarios/ClientFund.js
- test/scenarios/ERC20TransferController.js
- test/scenarios/ERC721TransferController.js
> Add function standard() to transfer controllers

- contracts/DriipSettlementByPayment.sol
- test/scenarios/DriipSettlementByPayment.js
> Replace stageToBeneficiary() by transferToBeneficiary()

- contracts/ClientFund.sol
- contracts/DriipSettlementByPayment.sol
- contracts/NullSettlement.sol
- package.json
- test/scenarios/NullSettlement.js
> Add standard parameter to null settlement functions

- contracts/DriipSettlementByPayment.sol
- contracts/DriipSettlementChallengeByPayment.sol
- contracts/NullSettlement.sol
- scripts/node/require-enumerate.js
- test/scenarios/DriipSettlementChallengeByPayment.js
> Constrain start of DSC by payment by wallet nonce

- contracts/NullSettlementState.sol
- contracts/TransferControllerManager.sol
- migrations/1_initial_migration.js
- migrations/3_libraries.js
- migrations/5_bulk_of_contracts.js
- package.json
Prepare for migration to mainnet of v1.3.0.
> Mainnet migration

- contracts/DriipSettlementByPayment.sol
- contracts/DriipSettlementByTrade.sol
- package.json
- scripts/node/require-enumerate.js
- test/scenarios/DriipSettlementByTrade.js
> Support standard parameter in trade settlement

- contracts/DriipSettlementByPayment.sol
- contracts/DriipSettlementChallengeByPayment.sol
- contracts/DriipSettlementChallengeByTrade.sol
- contracts/test/MockedDriipSettlementChallengeState.sol
- migrations/5_bulk_of_contracts.js
- test/scenarios/DriipSettlementChallengeByTrade.js
> Support unsynchronized balance in trade at start of DSC

- contracts/DriipSettlementChallengeByTrade.sol
- test/scenarios/DriipSettlementChallengeByTrade.js
Solution to #360, #361 and #362.
> Add and update events in DriipSettlementChallengeByTrade

- contracts/DriipSettlementChallengeByPayment.sol
- contracts/DriipSettlementChallengeByTrade.sol
- contracts/test/MockedNullSettlementChallengeState.sol
- test/scenarios/DriipSettlementChallengeByTrade.js
> Cancel dependent NSC when cancelling DSC in DriipSettlementChallengeByTrade

- contracts/DriipSettlementByTrade.sol
- test/scenarios/DriipSettlementByTrade.js
> Terminate DSC proposals at successful settlement of trade

- contracts/DriipSettlementChallengeByPayment.sol
- contracts/DriipSettlementState.sol
- test/scenarios/DriipSettlementChallengeByPayment.js
> Update correction of cumulative relative transfer at start of challenge

- contracts/DriipSettlementByPayment.sol
- contracts/DriipSettlementChallengeByPayment.sol
- contracts/DriipSettlementState.sol
- contracts/FungibleBalanceLib.sol
- contracts/test/MockedDriipSettlementState.sol
- migrations/5_bulk_of_contracts.js
- test/scenarios/DriipSettlementByPayment.js
- test/scenarios/DriipSettlementChallengeByPayment.js
- test/scenarios/DriipSettlementState.js
> Store settled amount by block numbered records

- package.json
* Generalized postinstall script
> Fix postinstall scrpt

- .npmrc
- contracts/DriipSettlementByPayment.sol
- contracts/TokenHolderRevenueFund.sol
- contracts/test/MockedBeneficiary.sol
- package.json
- test/mocks.js
- test/scenarios/DriipSettlementByPayment.js
- test/scenarios/TokenHolderRevenueFund.js
Solution to #446, #447 and #449.
> TokenHolderRevenueFund claimable and claimed amounts

- contracts/BalanceAucCalculator.sol
- contracts/RevenueToken.sol
- contracts/TokenHolderRevenueFund.sol
- migrations/3_libraries.js
- migrations/5_bulk_of_contracts.js
- package.json
- test/scenarios/BalanceAucCalculator.js
- test/scenarios/NahmiiToken.js
- test/scenarios/TokenHolderRevenueFund.js
Final stage of transition to new nahmii token and refactoring of balance blocks calculation.
> Pre-release of v1.5.0-ropsten.2
